version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ca:f5:3c:0a:78:51:24:60:8b:19:4a:59:c0:bf:52:ce"
      - run:
          name: Run tests
          command: |
            ssh beep@51.15.25.60 mkdir kek
            
workflows:
  sample:
    jobs:
      - build
