version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            ssh beep@51.15.25.60 mkdir kek
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:  
          requires:
            - build
